### ISSUE TITLE
A user without password can be created

### ISSUE THREAD

**Issue by cjoohs** [opinsys/puavo-users#95]
Users can be created without a password in puavo-users. Not sure if this is a wanted feature, but it can cause situations where user is accidentally created without a password and that user can't log in.

Case:
School administrator tries to create a new user, fills all the needed information but forgets to select a role. This try ends to an error that says adding a user has failed. (Actually this is another problem that it is not clear what information is missing). At this point the password fields are emptied! 
After the error, the school admin now selects the role and presses enter or maybe scrolls down and clicks "Create" and does not notice that passwords are missing. New user is created without a password and it's not working.

If this operation is not needed, it should be removed/fixed. At least there should be a notification about the action that passwordless user is going to be created.

**Comment by jarmopi** [comment]
After some discussion, we've decided that it should be possible to create users without passwords. Forcing passwords would also cause problems when external logins are used.
